# Numpy exercises

In [ ]:
# Import package
import numpy as np

In [7]:
# a. Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1 
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# b. Create a vector with values ranging from 10 to 49
range_vector = np.arange(10,50)
print(range_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# c. Reverse a vector (first element becomes last)
vector = np.arange(10)
reverse_vector = vector[::-1]
print(reverse_vector)

[9 8 7 6 5 4 3 2 1 0]


In [10]:
# d. Create a 3x3 matrix with values ranging from 0 to 8
range = np.arange(9)
matrix_range = range.reshape(3,3)
print(matrix_range)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
# e. Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
i = np.where(x==0)[0]
print(i)

[2 3 5]


In [37]:
# f. Create a random vector of size 30 and find the mean value
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print(mean_value)

0.5502147654043021


In [46]:
# g. Create a 2d array with 1 on the border and 0 inside
border_array = np.zeros((5,10), dtype='int16')
border_array[:,[0,-1]] = 1
print(border_array)

[[1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]]


In [54]:
# h. Create a 8x8 matrix and fill it with a checkerboard pattern
checker_board = np.zeros((8,8), dtype='int16')
checker_board[::2, ::2] = 1
checker_board[1::2, 1::2] = 1
print(checker_board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [60]:
# i. Create a checkerboard 8x8 matrix using the tile function
x = np.array([[1,0],[0,1]])
x = np.tile(x, (4,4))
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [63]:
# j. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z = np.delete(Z, np.logical_and(Z>3, Z<8))
print(Z)

[ 0  1  2  3  8  9 10]


In [65]:
# k. Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.00318471 0.00849995 0.03852696 0.05121483 0.14794425 0.46190629
 0.65456293 0.71812841 0.8053625  0.83341592]


In [121]:
# l. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

print(A)
print(B)
print(A==B)

True
[1 1 1 1 0]
[1 1 1 1 0]
[ True  True  True  True  True]


In [126]:
# m. How to calculate the square of every number in an array in place (without creating temporaries)?
Z = np.arange(10, dtype=np.int32)
print(Z.dtype, Z)
Z *= Z
print(Z.dtype, Z)

int32 [0 1 2 3 4 5 6 7 8 9]
int32 [ 0  1  4  9 16 25 36 49 64 81]


In [129]:
# n. How to get the diagonal of a dot product?
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(D)

[ 18  66 132]
